### ISSUE TITLE
add vk conversations

### ISSUE THREAD

**Issue by alexanderStoyak** [rus-anonym/rus-anonym.github.io#10]
https://search-for-chats-of-vk.ru/

**Comment by RusAnonym** [comment]
add vk conversation preview in https://github.com/rus-anonym/rus-anonym.github.io/commit/cc5507a3d1a46c2086d7237f0fe3859ff8c08a04

**Comment by RusAnonym** [comment]
after fixing cors from API side, add loading from API

**Comment by RusAnonym** [comment]
add loading from API in https://github.com/rus-anonym/rus-anonym.github.io/commit/b31c61c83747ae1728d1f27202e58483571e5141

**Comment by RusAnonym** [comment]
made the buttons work in https://github.com/rus-anonym/rus-anonym.github.io/commit/bcde845c41f8cf5f427ad8d94204c8842501a3da

**Comment by RusAnonym** [comment]
add sort in https://github.com/rus-anonym/rus-anonym.github.io/commit/6c151f3fe2fe9c946f4d8053c2e5271642b36e42

**Comment by RusAnonym** [comment]
initially sort from newest to oldest by publication date

**Comment by depre33edBoy** [comment]
I propose to make an endless feed on the site in the convertsations site, just like in the Cat section.
Also add switches between pages and ribbon. So that the user can choose how it is convenient for him

**Comment by RusAnonym** [comment]
add endless feed in https://github.com/rus-anonym/rus-anonym.github.io/commit/547b205cc431e0c2d23492eba0eab45a8c776403

**Comment by RusAnonym** [comment]
- [ ] add button for random conversation display

**Comment by RusAnonym** [comment]
close in https://github.com/rus-anonym/rus-anonym.github.io/commit/dfc2efac307db2acd664950aeda941d93cb2ee83
moved to https://vk.com/app51408389_675114166
