### ISSUE TITLE
In panel Main (/#/) clicking on all buttons except donat does not work

### ISSUE THREAD

**Issue by kravetsone** [rus-anonym/rus-anonym.github.io#19]
# Please fix

**In panel [Main](https://rus-anonym-team.ru/#/) ([/#/](https://rus-anonym-team.ru/#/)) clicking on all buttons except donat does not work.**

### **_The video below is proof of this:_**
https://user-images.githubusercontent.com/57632712/199304557-2d487de5-78d7-4cad-a0c5-730ff217ddd2.mp4

**Comment by RusAnonym** [comment]
fu***ng vk ui
