### ISSUE TITLE
API for Users Source Code

### ISSUE THREAD

**Issue by n1k1ta-romanov** [rus-anonym/rus-anonym.github.io#8]
Написать небольшой API модуль, в котором будут методы:
- [ ] 1. articles.search, Params: title: string - название статьи || id: number - номер статьи, Response: text: string - текст статьи, title: string - название статьи, id: number - номер статьи
- [ ] 2. loveMemeGenerator, Params: title: string - название мема || id: number - номер мема, Response: text: string - текст мема, title: string - название мема, id: number - номер мема

**Comment by RusAnonym** [comment]
Это статический сайт, не имеющий бекенда
